### PR TITLE
Imp pabi chartfield invoiceline hr view

### PR DESCRIPTION
**Pull request by mra-odoo**
Hi Kitti,

Enhance addon "pabi_chartfield" to create detail view for Customer / Supplier Invoice Line and HR Expense Line.

Ref: Issues/623

Thanks,

### CODE REVIEW

**Comment by pabi2** [comment]
Hi Mustu, can you help check Travis first? I see it as fixable from your side.

**Comment by mra-odoo** [comment]
Hi Kitti,
Yes we are checking it.
Thanks,

**Comment by mra-odoo** [comment]
It was by mistake.

**Comment by pabi2** [comment]
Hi Mustu, it is a bit weird. Here is how I do.

- In Thai Mode
- Create new Title in Thai = "กกกกกก"
- Click Translate Dialog, and change source to "AAAAA" -> ok, the translation table already created correctly.

image


- But when I save the record, now Thai mode show "AAAAA" -> Weird as the translation table already correct.

image

If I click the icon again, it show only AAAAA -> it is strang, as the translation above already have 2 langs.
 
image

????

**Pull request merged**
